import {useEffect,useMemo,useState} from "react";
import axios from "axios";
import {Chart as ChartJS,CategoryScale,LinearScale,PointElement,LineElement,Tooltip,Legend} from "chart.js";
import {Line} from "react-chartjs-2";
import "./index.css";
ChartJS.register(CategoryScale,LinearScale,PointElement,LineElement,Tooltip,Legend);
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0);

function Stat({title,value,sub}){return <div className="card p-5"><div className="text-sm text-slate-500">{title}</div><div className="text-3xl font-black mt-2">{value}</div><div className="text-xs text-slate-400 mt-1">{sub}</div></div>}

export default function App(){
 const [summary,setSummary]=useState(null),[routes,setRoutes]=useState([]),[route,setRoute]=useState("MAA-DEL"),[forecast,setForecast]=useState(null),[status,setStatus]=useState("");
 async function load(){const [s,r,f]=await Promise.all([axios.get(`${API}/api/summary`),axios.get(`${API}/api/routes`),axios.get(`${API}/api/forecast?route=${route}`)]);setSummary(s.data);setRoutes(r.data);setForecast(f.data)}
 useEffect(()=>{load().catch(()=>setStatus("Backend is starting... refresh in a few seconds."))},[]);
 useEffect(()=>{axios.get(`${API}/api/forecast?route=${route}`).then(x=>setForecast(x.data)).catch(()=>{})},[route]);
 const selected=routes.find(x=>x.route===route);
 const chartData=useMemo(()=>{if(!forecast)return null;const labels=[...forecast.history.map(x=>x.date),...forecast.forecast.map(x=>x.date)];const h=forecast.history.map(x=>x.value);return {labels,datasets:[{label:"Observed average fare",data:[...h,...Array(forecast.forecast.length).fill(null)],borderWidth:3,tension:.35,pointRadius:0},{label:"Forecast",data:[...Array(Math.max(0,h.length-1)).fill(null),h.at(-1),...forecast.forecast.map(x=>x.value)],borderWidth:3,borderDash:[7,7],tension:.35,pointRadius:0}]};},[forecast]);
 async function scrape(){setStatus("Collecting fare observations...");try{const r=await axios.post(`${API}/api/scrape/run`);setStatus(`${r.data.inserted} observation(s) collected.`);await load()}catch{setStatus("Collection failed. Check backend.")}}
 async function exportCsv(){try{const r=await axios.get(`${API}/api/export/csv?route=${route}`);const blob=new Blob([r.data.content],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=r.data.filename;a.click();URL.revokeObjectURL(url)}catch{setStatus("Export failed.")}}
 return <div className="min-h-screen">
 <header className="bg-[#102b49] text-white"><div className="max-w-7xl mx-auto px-6 py-5 flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="text-xs tracking-[.2em] uppercase text-sky-200">Smart India Hackathon 2026 • SIH26056</div><h1 className="text-3xl md:text-4xl font-black mt-1">✈️ AirIntel India</h1><p className="text-slate-300 mt-1">Real-time Airfare Price Intelligence</p></div><div className="flex gap-2"><button onClick={scrape} className="px-4 py-2 rounded-xl bg-white text-[#102b49] font-bold">Run Demo Scrape</button><button onClick={exportCsv} className="px-4 py-2 rounded-xl border border-white/30 font-bold">Export CSV</button></div></div></header>
 <main className="max-w-7xl mx-auto px-6 py-8 space-y-7">{status&&<div className="card px-4 py-3 text-sm text-slate-600">{status}</div>}
 <section className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-5 gap-4"><Stat title="National APIx" value={summary?.national_index??"—"} sub="Prototype national index"/><Stat title="Average Fare" value={summary?money(summary.avg_fare):"—"} sub="Across observations"/><Stat title="Observations" value={summary?.observations?.toLocaleString()??"—"} sub="Collected records"/><Stat title="Routes" value={summary?.routes??"—"} sub="Tracked city pairs"/><Stat title="Airlines" value={summary?.airlines??"—"} sub="Observed carriers"/></section>
 <section className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="card p-6 lg:col-span-2"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 mb-5"><div><h2 className="text-xl font-black">Airfare Trend & Forecast</h2><p className="text-sm text-slate-500">Historical average fare + 7-day forecast</p></div><select value={route} onChange={e=>setRoute(e.target.value)} className="border border-slate-300 rounded-xl px-3 py-2 bg-white font-semibold">{routes.map(r=><option key={r.route}>{r.route}</option>)}</select></div><div className="h-[340px]">{chartData&&<Line data={chartData} options={{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}},scales:{y:{ticks:{callback:v=>`₹${Number(v).toLocaleString("en-IN")}`}}}}}/>}</div></div>
 <div className="card p-6"><h2 className="text-xl font-black">Route Snapshot</h2><p className="text-sm text-slate-500 mt-1">Current route-level intelligence</p><div className="mt-6 space-y-5"><div><div className="text-xs text-slate-500">Route</div><div className="text-2xl font-black">{selected?.route||"—"}</div></div><div><div className="text-xs text-slate-500">Average fare</div><div className="text-2xl font-black">{selected?money(selected.avg_fare):"—"}</div></div><div><div className="text-xs text-slate-500">APIx</div><div className="text-4xl font-black text-sky-700">{selected?.index??"—"}</div><div className="text-xs text-slate-400">Base = 100</div></div><div><div className="text-xs text-slate-500">Observations</div><div className="text-lg font-bold">{selected?.observations?.toLocaleString()||"—"}</div></div></div></div></section>
 <section className="card overflow-hidden"><div className="p-6 border-b border-slate-200"><h2 className="text-xl font-black">National Route Coverage</h2><p className="text-sm text-slate-500">Tracked city-pair routes in the prototype.</p></div><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-6 py-4">Route</th><th className="px-6 py-4">Avg Fare</th><th className="px-6 py-4">APIx</th><th className="px-6 py-4">Observations</th></tr></thead><tbody>{routes.map(r=><tr key={r.route} className="border-t border-slate-100"><td className="px-6 py-4 font-bold">{r.route}</td><td className="px-6 py-4">{money(r.avg_fare)}</td><td className="px-6 py-4 font-bold">{r.index}</td><td className="px-6 py-4">{r.observations}</td></tr>)}</tbody></table></div></section>
 <section className="grid md:grid-cols-4 gap-4">{[["🕷️","Automated Collection","Playwright collection layer"],["🧹","Data Cleaning","Standardized observations"],["📈","APIx","Route-wise + national intelligence"],["🤖","Forecasting","Future fare trend estimation"]].map(x=><div className="card p-5" key={x[1]}><div className="text-3xl">{x[0]}</div><div className="font-black mt-3">{x[1]}</div><div className="text-sm text-slate-500 mt-1">{x[2]}</div></div>)}</section>
 <footer className="text-center text-xs text-slate-400 py-4">AirIntel India • BYTE_STORM • SIH26056 • Prototype</footer></main></div>
}
